### ISSUE TITLE
No Component Found for view with name "ARTSurfaceView"

### ISSUE THREAD

**Issue by drewbaumann** [nerdyfactory/react-native-simple-gauge#1]
Hey thanks for creating this. I was trying to implement it with my project, but ran into this error. Unfortunately I am new to react native so my debug skills are infantile, but I thought I would report the issue and share a screenshot of the error:

![image](https://cloud.githubusercontent.com/assets/337808/17459963/45b50476-5c05-11e6-8ba0-56bd8ec4b822.png)

**Comment by vinayr** [comment]
If you are using iOS you have to link ART library to your project. This is explained [here](https://github.com/bgryszko/react-native-circular-progress#installation).
I will update README sometime soon.

**Comment by drewbaumann** [comment]
Yep. You are correct!
![facepalm](http://www.bluehogreport.com/wp-content/uploads/facepalm.jpg)

I have made a PR to clear this up for future users: #2

**Comment by vinayr** [comment]
Thanks @drewbaumann
