### ISSUE TITLE
backgroundColor no longer works

### ISSUE THREAD

**Issue by jayesbe** [nerdyfactory/react-native-simple-gauge#10]
I just updated.. not sure if the most recent update changed something.. but I noticed the backgroundColor no longer fills.. its just transparent. 

I have both a tintColor and backgroundColor.  If I set the tintColor to blue for example and the backgroundColor to red, and have a fill of 80%. The 80% portion of the circle is blue while the 20% portion is now transparent. Previously it would be red which is what I am expecting.

**Comment by jayesbe** [comment]
Downgraded to 0.1.2 and its working as expected.

**Comment by jayesbe** [comment]
Actually I see the issue now.. its because 0.1.2 works on RN 0.44 while 0.1.3 works on 0.45.

Upgraded RN to 0.45 and upgraded back to 0.1.3 and its all good now.

**Comment by JonghunYu** [comment]
@jayesbe Added comments on README.
Thanks for reporting
https://github.com/nerdyfactory/react-native-simple-gauge/commit/5409d76e0093e426a6666c6eb5af05fc8368eac8
