### ISSUE TITLE
Fill animation counter clockwise & fill start angle

### ISSUE THREAD

**Issue by storerjeremy** [nerdyfactory/react-native-simple-gauge#11]
Hi,

I am planning to add to this library so the fill animation can be counter clockwise in addition to it being clockwise and am also trying to modify it so the fill "start angle" can be defined so you can say begin the fill from say 180 and end it at 270.

Any tips on how to go about doing this?

Thanks

**Comment by JonghunYu** [comment]
Hi @storerjeremy 
you can switch startDegree and endDegree parameter from this function.
https://github.com/nerdyfactory/react-native-simple-gauge/blob/master/src/CircularProgress.js#L8-L14
I would really appreciate for your contribution.
