### ISSUE TITLE
console.error: "JSON value '<null>' of type NSNull cannot be converted to NSNumber"

### ISSUE THREAD

**Issue by boob1e** [nerdyfactory/react-native-simple-gauge#12]
when using debug remotely, app crashes at error. only happens with remote debugging on.

**Comment by JonghunYu** [comment]
@raytorres280 Hi I don't see the exception when I am running example. Could you give me more details such as react-native version, which debug tool you use?

**Comment by boob1e** [comment]
Hi I'm using the Chrome Tools. My version is 0.44.0. The debugger does not crash if I remove the gauges from the code.

**Comment by JonghunYu** [comment]
It seems you use the latest version of the library that doesn't support 0.44. Could you try to downgrade the version to 0.1.2?

**Comment by boob1e** [comment]
sorry react native version 0.44.0, gauges is already 0.1.2.

**Comment by boob1e** [comment]
Also, this only happens on Chrome dev tools. When I run react-devtools with react log-ios I don't have the error.

**Comment by JonghunYu** [comment]
@raytorres280 is this still an issue?

**Comment by boob1e** [comment]
yes still an issue. 0.44 react native. 0.1.2 gauges. chrome dev tools.

**Comment by JonghunYu** [comment]
@raytorres280 I have run the example with the version you said but it looks fine with the chrome dev tool. please check this branch https://github.com/nerdyfactory/react-native-simple-gauge/tree/bug-fix
