### ISSUE TITLE
Incorrect exports in index.js

### ISSUE THREAD

**Issue by ernanielyjr** [nerdyfactory/react-native-simple-gauge#14]
Your index.js works but this is incorrect. The right would be:

import { CircularProgress as GaugeProgress } from './src/CircularProgress';
import { AnimatedCircularProgress as AnimatedGaugeProgress } from './src/AnimatedCircularProgress';

export { GaugeProgress, AnimatedGaugeProgress };

**Comment by JonghunYu** [comment]
@ernanielyjr Hi Thanks for reporting. We would be glad to have PR from you.
