### ISSUE TITLE
Add line over the gauge

### ISSUE THREAD

**Issue by ShaikhKabeer** [nerdyfactory/react-native-simple-gauge#18]
Hi,
How do I add the line over circular gauge like below

![half doughnut](https://user-images.githubusercontent.com/29751540/33873112-b2efb50e-df3f-11e7-8c6d-d8c600bdd98f.png)

My code is here

import { AnimatedGaugeProgress, GaugeProgress } from 'react-native-simple-gauge';
import React,{Component} from 'react';
import {View,Text,StyleSheet} from 'react-native';

export default class App extends React.Component{
  render(){
    return(
       <View style={styles.container}>     
      <AnimatedGaugeProgress
      size={200}
      width={20}
      fill={60}
      rotation={90}
      cropDegree={180}
      tintColor="#81BD26"
      //backgroundColor="#b0c4de"
      stroke={[2, 2]} //For a equaly dashed line
      strokeCap="square" />
      </View>
    )
  }
}

const styles=StyleSheet.create({
  container:{flex:1, justifyContent:'center', alignItems:'center'}
})

**Comment by ShaikhKabeer** [comment]
How can I do this as shown in above image ?

**Comment by ShaikhKabeer** [comment]
How can I do this as shown in above image ?

**Comment by JonghunYu** [comment]
I think you should manually draw the line added like drawing a circle.
https://github.com/nerdyfactory/react-native-simple-gauge/blob/master/src/GaugeProgress.js
Please note that the line need to be changed based on the fill prop to animation work.

**Comment by ShaikhKabeer** [comment]
Actually, I tried a lot but failed to do it. So can you please share the code if you know how to place that line. And one thing is that line could be at the different position on that Gauge. It'll be great if you help.

**Comment by JonghunYu** [comment]
I am sorry but I don't know how to draw the line as you want.
https://github.com/react-native-china/react-native-ART-doc/blob/master/doc.md
this is a documentation I found.
Hope this help
