### ISSUE TITLE
Gauge is disappearing on samsung Galaxy S6  device after screen unlocking

### ISSUE THREAD

**Issue by ShaikhKabeer** [nerdyfactory/react-native-simple-gauge#19]
I found one issue with the gauge like on Samsung Galaxy s6 device the gauge is disappearing after we lock unlock the device.what is the solution for this?

**Comment by JonghunYu** [comment]
I have no idea about that. Does it happen only in Galaxy S8?

**Comment by ShaikhKabeer** [comment]
Sorry, it is Galaxy s6. Changed comment from s8 to s6. @JonghunYu  it is happening in Galaxy s6

**Comment by JonghunYu** [comment]
did you check that the component was rendered correctly? maybe by leaving some log in render method

**Comment by ShaikhKabeer** [comment]
Yes, only after complete rendering of component I'm locking the device. But when recovering from lock to unlock then gauge is disappearing. This case is happening only with Samsung Galaxy S6 , but not with others

**Comment by ShaikhKabeer** [comment]
Solved this one by referring from this link. @JonghunYu  Please include this code in your library


https://github.com/bgryszko/react-native-circular-progress/blob/454048bd92a166b876d53ea227c6cff2cc43c41a/src/AnimatedCircularProgress.js
