### ISSUE TITLE
Exception: Error while updating property 'd' in shadow node of type: ARTShape

### ISSUE THREAD

**Issue by harshada-bhanose** [nerdyfactory/react-native-simple-gauge#23]
I am using this react-native-simple-gauge library in a project as below where the props fill is assigned a value calculated as percentage. If I assign a hard coded value like {30} to props fill, the code works perfectly. But with the calculated value it throws an exception:

_Error while updating property 'd' in shadow node of type: ARTShape

null

TypeError: expected dynamic type `double', but had type `null'
updateShadowNodeProp
    ViewManagersPropertyCache.java:113
setProperty
    ViewManagerPropertyUpdater.java:154
updateProps
    ViewManagerPropertyUpdater.java:58
updateProperties
    ReactShadowNodeImpl.java:298
updateView
    UIImplementation.java:309
updateView
    UIManagerModule.java:372
invoke
    Method.java
invoke
    Method.java:372
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818_

Sample code:
```javascript 
<AnimatedGaugeProgress    
    size={300}
    width={5}
    prefill={70}
    fill={parseFloat(percentage_marks)}
    rotation={90}
    cropDegree={120}
    tintColor="#D6E1F1"
    backgroundColor="#F2F4F7"
    stroke={[2, 2]} //For a equaly dashed line
    strokeCap="circle" >
        {(fill) => (
            <View style={{position:'absolute', top: 20, left: 5, width: 290, height: 140, alignItems: 'center', justifyContent: 'center'}}>
                <Text style={styles.lineText}>Your Score is {percentage_marks} %</Text>
            </View>
        )}
</AnimatedGaugeProgress>`
```
What can be the cause for this exception?

**Comment by JonghunYu** [comment]
@harshada-bhanose can you wrap the component like 
```js
{percentage_marks && <AnimatedGaugeProgress />}
```
to prevent empty percentage_marks?

**Comment by harshada-bhanose** [comment]
@JonghunYu I tried your suggestion and now the exception is related to the child node (In my case I have a View containing Text as child) I guess. Here is the exception:

Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
addChildAt
    ReactShadowNodeImpl.java:199
addChildAt
    ReactShadowNodeImpl.java:54
setChildren
    UIImplementation.java:472
setChildren
    UIManagerModule.java:436
invoke
    Method.java
invoke
    Method.java:372
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:739
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:135
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:818

There is no exception if I remove the child view.

**Comment by JonghunYu** [comment]
@harshada-bhanose can you try with 
```js
{!!percentage_marks && <AnimatedGaugeProgress />}
```
https://github.com/facebook/react-native/issues/13243#issuecomment-335488473

**Comment by harshada-bhanose** [comment]
@JonghunYu Double Negation solved the problem...thanks a lot !!

**Comment by harshada-bhanose** [comment]
@JonghunYu Above problem is solved but now the gauge is not shown if the percentage_marks (fill prop) is zero because of the double negation condition. We have to show the progress gauge even if the fill is zero. Can you please help how this can be done?

**Comment by JonghunYu** [comment]
You could try with var ```!== undefined``` or something like that

**Comment by harshada-bhanose** [comment]
@JonghunYu Tried comparing with undefined, but it gives back the original exception again

Error while updating property 'd' in shadow node of type: ARTShape
null
TypeError: expected dynamic type double', but had typenull'

**Comment by JonghunYu** [comment]
```js
!!percentage_marks || percentage_marks === 0
```
will solve the problem

**Comment by harshada-bhanose** [comment]
@JonghunYu It woks....thanks !!!
