### ISSUE TITLE
Gauge disappearing on locking (Android 7.1.2)

### ISSUE THREAD

**Issue by fnusneha** [nerdyfactory/react-native-simple-gauge#24]
I'm using an AnimatedGaugeProgress on a page. And in Android 7.1.2, on locking the phone, the gauge disappears completely.

Reopening the activity shows the gauge back again. Not happening in Android O.

This is sample JS for how I'm using the gauge.
                      

```
  <AnimatedGaugeProgress
                        fill={value}
                        rotation={90}
                        tintColor={this.props.gaugeColor}
                        backgroundColor="#D8D8D8"
                        stroke={[2, 2]} //For a equaly dashed line
                        strokeCap="circle"
                        size={size}
                        width={width}
                        cropDegree={cropDegree}>
                        {(fill) => (....)}
                        </AnimatedGaugeProgress>
```

Is this a known issue? What's the solution?

**Comment by JonghunYu** [comment]
@fnusneha does it happen again when you replace the component with normal `<View/>`?

**Comment by ClayChristmas** [comment]
@JonghunYu - do you mean just replacing it with a generic view instead of the AnimatedGaugeProgress and seeing if that view disappears?  We are seeing this in multiple scenarios where everything else on the screen renders (views, text, images) without issues including the content of the fill function for the gauge, but the gauge disappears.

**Comment by JonghunYu** [comment]
@ClayChristmas than could you check the fill function is executed while others are rendered

**Comment by ClayChristmas** [comment]
@JonghunYu - sorry for the delay in getting back to you.  This is still an issue for us, but we had to work on a few other things for a release.  I just got a chance to run the test, and the fill method is not being called when this occurs.  It gets called normally, but if I lock the screen and unlock it then it does not get called again when the screen gets unlocked.
