### ISSUE TITLE
Failed to dispatch window animation state change

### ISSUE THREAD

**Issue by hotshine** [nerdyfactory/react-native-simple-gauge#25]
안녕하세요~~

  "dependencies": {
    "react": "16.3.0-alpha.1",
    "react-native": "0.54.0",
    "react-native-simple-gauge": "^0.1.7",
    "react-native-svg": "^6.2.2",
    "react-native-svg-charts": "^4.0.0"
  },

      <View style={styles.container}>
        <View style={styles.gaugeBottom}>
          <View style={styles.rowItem}>
            <AnimatedGaugeProgress
              size={50}
              width={3}
              fill={100}
              rotation={0}
              cropDegree={90}
              tintColor="#4682b4"
              backgroundColor="#b0c4de" />
          </View>
        </View>
      </View>

npm init 테스트폴더
npm i --save react-native-simple-gaug

안드로이드 스튜디오 에뮬레이터에서 실행하면 
에러메세지도 뜨지않고 앱이 강제종료 됩니다.

"Warning: componentWillReceiveProps is deprecated and will be removed in the next major version. Use static getDerivedStateFromProps instead.
                                                  
                                                  Please update the following components: View"

"Failed to dispatch window animation state change"
안드로이드 스튜디오 logcat 에 보면 이런 메세지가 떠있는데
혹시 같은현상 해결하신 적 있으신가요??

**Comment by JonghunYu** [comment]
@hotshine 안녕하세요 컴포넌트 빼고 돌려봐도 죽나요?

**Comment by hotshine** [comment]
윈도우랑 맥북에서 똑같이 init 해서 폴더만들어 실행해봤는데
맥북에선 잘되네요...
윈도우에서 안되는건지 이 노트북이 이상한건지 ㅠㅠ
해결?되었습니다  감사합니다 ^^
