### ISSUE TITLE
children object is an array and not a function

### ISSUE THREAD

**Issue by ghost** [nerdyfactory/react-native-simple-gauge#26]
Hi,
When doing something like this:
`<GaugeProgress ...>{()=><Text>Test</Text>}</GaugeProgress>`
An error occurred children is not a function and indeed children is an array like this:
`[" ", f()]`

I'm using RN version 0.52.2
Thanks,
Eran

**Comment by JonghunYu** [comment]
@eranbaroz can you try with 
```
<GaugeProgress ...>{()=>(<Text>Test</Text>)}</GaugeProgress>
```

I don't think it's package's problem

**Comment by ghost** [comment]
@JonghunYu I did try almost every available variation of expressions. Still get this error:
TypeError: children is not a function
```
This error is located at:
    in GaugeProgress (at index.js:45)
    in RCTView (at View.js:71)
    in View (at createAnimatedComponent.js:147)
    in AnimatedComponent (at TouchableOpacity.js:245)
    in TouchableOpacity (at index.js:44)
    in RCTView (at View.js:71)
    in View (at index.js:42)
    in LeaseState (at index.js:128)
    in RCTView (at View.js:71)
    in View (at index.js:119)
    in RCTView (at View.js:71)
    in View (at index.js:116)
    in EnabledAccounts (at index.js:50)
    in RCTView (at View.js:71)
    in View (at index.js:46)
    in IAMSafety (at SceneView.js:17)
    in SceneView (at DrawerScreen.js:21)
    in DrawerScreen (at withCachedChildNavigation.js:69)
    in withCachedChildNavigation(DrawerScreen) (at DrawerNavigator.js:71)
    in Unknown (at createNavigator.js:13)
    in Navigator (at DrawerView.js:178)
    in RCTView (at View.js:71)
    in View (at DrawerLayoutAndroid.android.js:186)
    in AndroidDrawerLayout (at DrawerLayoutAndroid.android.js:200)
    in DrawerLayoutAndroid (at DrawerView.js:158)
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at index.js:18)
    in Main (at renderApplication.js:35)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:71)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
GaugeProgress.render
    C:\dev\mobile_application\node_modules\react-native-simple-gauge\src\GaugeProgress.js:53:22
GaugeProgress.proxiedMethod
    C:\dev\mobile_application\node_modules\react-proxy\modules\createPrototypeProxy.js:44:29
finishClassComponent
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:7866:30
updateClassComponent
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:7833:11
beginWork
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:8284:15
performUnitOfWork
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:10513:15
workLoop
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:10584:25
Object._invokeGuardedCallback
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:134:9
invokeGuardedCallback
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:67:26
renderRoot
    C:\dev\mobile_application\node_modules\react-native\Libraries\Renderer\ReactNativeRenderer-dev.js:10677:6
 ```

**Comment by ghost** [comment]
@JonghunYu 
Can you please add an example code that use the GaugeProgress in this way?
(and off cours make sure it works :) )
Thanks,
Eran

**Comment by ghost** [comment]
@JonghunYu 
I think the use of children as function is unnecessary.
In React: 

> Since this.props.children can have one element, multiple elements, or none at all, its value is respectively a single child node, an array of child nodes or undefined

[Link to the article on React props children: https://learn.co/lessons/react-this-props-children](https://learn.co/lessons/react-this-props-children)
So prop typing the children is not aligned to React methodology.

I'm creating a pull request for you to overview and and see what I think should be the code for children.
Can you please write back what is the use for children as a function?
Thanks,
Eran

**Comment by JonghunYu** [comment]
@eranbaroz 
The reason why the component only accept function as a children is that it's the easiest way to pass fill value to children.
If you want the component to accept other components as children, you should create a wrapping component and render the wrapping component inside while pass fill props.
please refer to following codes
https://github.com/nerdyfactory/react-native-simple-gauge/blob/master/src/GaugeProgress.js#L52-L54
https://stackoverflow.com/questions/32370994/how-to-pass-props-to-this-props-children

I'd love if you create new PR for this

**Comment by ghost** [comment]
@JonghunYu 
I can set the component to accept the following types as children: function, array, object.
Just keep in mind that from OOP point of view - for a component to communicate out itself properties is not the best practice. 
Any way for the sake of old users who use the function method I'll create a new pull request.

**Comment by JonghunYu** [comment]
@eranbaroz please try with the latest version
