### ISSUE TITLE
Gauge disappearing on locking

### ISSUE THREAD

**Issue by Hvkvn** [nerdyfactory/react-native-simple-gauge#31]
Hello, when i lock my Android 7.1.1 then unlock it. the gauge disappears.
I saw an Issue was opend but there is still no solution for this Bug.

                <AnimatedGaugeProgress
                    size={size}
                    width={width}
                    fill={this.state.fill}
                    rotation={90}
                    cropDegree={cropDegree}
                    tintColor="#007aff"
                    backgroundColor="#ff0008"
                    stroke={[2, 2]}
                </AnimatedGaugeProgress>

**Comment by JonghunYu** [comment]
Hi Thanks for reporting.
Will take a look

**Comment by Hvkvn** [comment]
Any Solution ?

**Comment by JonghunYu** [comment]
@Hvkvn sorry for late reply. can you try with the latest version? 
Please reopen the issue if the bug still exists
