### ISSUE TITLE
Animated.Value "fill" prop

### ISSUE THREAD

**Issue by psyzz** [nerdyfactory/react-native-simple-gauge#32]
hello, when i'm using an Animated.Value for the "fill" prop, the animation works but i get the warning:
Invalid prop `fill` of type `object` supplied to `AnimatedGaugeProgress`, expected `number`

```

Animated.timing(this.state.fillProgress, {
      duration: 500,
      toValue: 0,
      useNativeDriver: false
 }).start();


<AnimatedGaugeProgress
  style={{ position: "absolute" }}
  size={90}
  width={5}
  fill={this.state.fillProgress}
  rotation={-90}
  cropDegree={0}
/>


```

**Comment by psyzz** [comment]
Maybe change _fill: PropTypes.number_ to _PropTypes.any_ or a better PropTypes ?

**Comment by JonghunYu** [comment]
Hi could you let me know the version number of the package?

**Comment by psyzz** [comment]
"version": "0.1.10"

**Comment by JonghunYu** [comment]
ah I misunderstood.
you can just pass number not `Animated` value.

**Comment by psyzz** [comment]
but it works with Animated value

**Comment by JonghunYu** [comment]
https://github.com/nerdyfactory/react-native-simple-gauge/blob/master/src/AnimatedGaugeProgress.js#L33-L47
yes but it created a `Animated` inside the component so that would be redundancy.

**Comment by psyzz** [comment]
you right i'll try to make some changed so we can add our own animated value

**Comment by JonghunYu** [comment]
Sure I'd appreciate it

**Comment by psyzz** [comment]
#33

**Comment by JonghunYu** [comment]
close due to inactivity
