### ISSUE TITLE
How to draw a chart like this using this library???

### ISSUE THREAD

**Issue by MohithHasan** [nerdyfactory/react-native-simple-gauge#34]
![circulargauge](https://user-images.githubusercontent.com/34531234/39613960-b20e422c-4f8d-11e8-82ec-163b02bbe9a3.PNG)

**Comment by JonghunYu** [comment]
close due to inactivity

**Comment by mohity777** [comment]
Hey did u find any solution ?>

**Comment by ixsamar** [comment]
Hi did you find any solution ?
