### ISSUE TITLE
Image inside Gauge is not showing

### ISSUE THREAD

**Issue by ghost** [nerdyfactory/react-native-simple-gauge#37]
When doing something like the following code: adding Image inside the Gauge component, the image is not showing. If doing the same with Text the text appears correctly.

```
<GaugeProgress
        size={size}
        width={width}
        fill={this.state.fill}
        cropDegree={cropDegree}
        ......
      >
        <View style={styles.textView}>
          <Image source={require('...some path to image file...')} />
        </View>
</GaugeProgress>
```

**Comment by AylwSt01** [comment]
i found that the view in which the gauge component sits, needs to have a transparent backgroundColor for anything to display inside the gauge.
I hope this helps you... the author seems to be non-responsive right now!

**Comment by JonghunYu** [comment]
close due to inactivity
