### ISSUE TITLE
Add duration prop and timing animation

### ISSUE THREAD

**Issue by sgovindan** [nerdyfactory/react-native-simple-gauge#39]
In a case, where the circle start at angle 0 and completes at 360 degree with some duration. It can have duration property to say how long this animation can happen. 

And If there can be any type for having different type of animations like timing as below, spring etc., It would be helpful.
**_animationType: propTypes.oneOf(Object.keys(AnimationType),
duration?: number,_**
and the **_animationType_** values would be:
**_AnimationType = {
timing: "timing",
spring: "spring",
}_**

Example animation:
_**if (this.props.animationType === AnimationType.timing) {
          Animated.timing(
              chartFillAnimation,
              {
                  toValue: this.props.fill,
                  duration: this.props.duration,
              }
          ).start(onAnimationComplete);
      }**_

**Comment by JonghunYu** [comment]
Hi sorry for late reply. PR is welcome.

**Comment by JonghunYu** [comment]
close due to inactivity
