### ISSUE TITLE
Gauge disappearing when app is in background / ios

### ISSUE THREAD

**Issue by NemanjaManot** [nerdyfactory/react-native-simple-gauge#40]
When application is in switch mode / background GaugeProgress (or AnimatedGaugeProgress) is not displayed.

![111](https://user-images.githubusercontent.com/18553180/44980815-38911e80-af71-11e8-9dae-72afe61f40ea.png)

![222](https://user-images.githubusercontent.com/18553180/44980821-3b8c0f00-af71-11e8-83ab-a1536ed97de1.png)

**Comment by JonghunYu** [comment]
Hi what version are you using?

**Comment by NemanjaManot** [comment]
Hello @JonghunYu 

react-native-simple-gauge: 0.1.10
react-native: 0.55.2

**Comment by NemanjaManot** [comment]
@JonghunYu  any news ?

**Comment by tsvetan-ganev** [comment]
I think it has something to do with this line: 
https://github.com/nerdyfactory/react-native-simple-gauge/blob/3aad7bdb8bd69e330ddb8b52083e2d36aa83427d/src/GaugeProgress.js#L22

It works fine in Android, so it might be iOS specific thing with the Application State.

@JonghunYu, what's the reason to check for the application state at all - what's the use-case of not showing the component when the state is not `'active'`? Does it have something to do with the animations?

**Comment by NemanjaManot** [comment]
@JonghunYu nothing?

**Comment by tsvetan-ganev** [comment]
@NemanjaManot, I forked the repo and did some changes, you can have a look here - https://github.com/ApiHawk/react-native-simple-gauge/commit/b67a443fcaba97d838668cd5d5dac9857fb018c7. It works fine for my use-case so far.

**Comment by NemanjaManot** [comment]
@tsvetan-ganev  it is working for me, thanks
