### ISSUE TITLE
Invariant Violation: Tried to register two views with the same name ARTSurfaceView

### ISSUE THREAD

**Issue by eduxsolano** [nerdyfactory/react-native-simple-gauge#57]
Dependencies:

`{
  "name": "******",
  "version": "2.0.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "postinstall": "jetify"
  },
  "dependencies": {
    "@ptomasroos/react-native-multi-slider": "^2.2.0",
    "@react-native-community/async-storage": "^1.8.1",
    "@react-native-community/checkbox": "^0.3.0",
    "@react-native-community/datetimepicker": "^2.2.2",
    "@react-native-community/google-signin": "^3.0.4",
    "@react-native-community/masked-view": "^0.1.7",
    "@react-native-firebase/app": "^6.3.4",
    "@react-native-firebase/auth": "^6.3.4",
    "@react-native-firebase/firestore": "^6.3.4",
    "@react-native-firebase/messaging": "^6.3.4",
    "@react-navigation/drawer": "^5.1.0",
    "@react-navigation/native": "^5.0.8",
    "@react-navigation/stack": "^5.1.0",
    "@types/react-native-fbsdk": "^1.0.0",
    "async-mutex": "^0.1.4",
    "axios": "^0.19.2",
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-ble-manager": "^7.1.4",
    "react-native-datepicker": "^1.7.2",
    "react-native-dialog": "^5.6.0",
    "react-native-elements": "^1.2.7",
    "react-native-fbsdk": "^1.1.2",
    "react-native-gesture-handler": "^1.6.0",
    "react-native-keep-awake": "^4.0.0",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-loading-spinner-overlay": "^1.1.0",
    "react-native-modal": "^11.5.4",
    "react-native-nordic-dfu": "^3.0.1",
    "react-native-notifications": "^3.1.2",
    "react-native-numeric-input": "^1.8.3",
    "react-native-picker-select": "^6.5.1",
    "react-native-progress": "^4.0.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-responsive-screen": "^1.4.0",
    "react-native-safe-area-context": "^0.7.3",
    "react-native-screens": "^2.2.0",
    "react-native-shapes": "^0.1.0",
    "react-native-simple-gauge": "^0.2.3",
    "react-native-switch-pro": "^1.0.4",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webview": "^8.1.2",
    "react-redux": "^7.2.0",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.12.0",
    "rxjs": "^6.5.4",
    "sprintf": "^0.1.5",
    "sprintf-js": "^1.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "@types/jest": "^24.0.24",
    "@types/ptomasroos__react-native-multi-slider": "^0.0.1",
    "@types/react-native": "^0.60.25",
    "@types/react-native-app-intro-slider": "^3.0.1",
    "@types/react-native-dialog": "^5.6.1",
    "@types/react-native-keep-awake": "^2.0.2",
    "@types/react-redux": "^7.1.7",
    "@types/react-test-renderer": "16.9.1",
    "@types/sprintf": "^0.1.0",
    "@typescript-eslint/eslint-plugin": "^2.12.0",
    "@typescript-eslint/parser": "^2.12.0",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "log-timestamp": "^0.3.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-native-cli": "^2.0.1",
    "react-test-renderer": "16.9.0",
    "typescript": "^3.7.3",
    "util": "^0.12.2"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
`

**Comment by JonghunYu** [comment]
@eduxsolano HI thanks for the report. you could give me more information?

**Comment by Bendetta** [comment]
Also seeing this. It's some sort of conflict with the `react-native-progress` library and the ART dependency.

**Comment by JonghunYu** [comment]
close due to inactivity
