### ISSUE TITLE
React Native ART was extracted out of RN 0.62

### ISSUE THREAD

**Issue by arambrosius** [nerdyfactory/react-native-simple-gauge#58]
React Native ART was extracted out of RN 0.62 into https://github.com/react-native-community/art which is causing a build issue. 

`Error: Unable to resolve module '../../react-native/Libraries/ART/ReactNativeART' from 'node_modules/react-native-simple-gauge/src/GaugeProgress.js'`

This started happening after upgrading react native from 0.61 to 0.62

**Comment by arambrosius** [comment]
PR to make it compatible with RN 0.62+ https://github.com/nerdyfactory/react-native-simple-gauge/pull/59

**Comment by ryan4664** [comment]
Any update on when this release is coming out?

**Comment by JonghunYu** [comment]
@ryan4664 Hi it's just published
