### ISSUE TITLE
Usage with Expo

### ISSUE THREAD

**Issue by wobsoriano** [nerdyfactory/react-native-simple-gauge#60]
Hello, can this be used in an expo app? Or do I have to eject?

I tried installing together with `art` but I'm still getting `No component found for view with name "ARTShape"`.

Thanks!

**Comment by JonghunYu** [comment]
@sorxrob Hi sorry for late reply. can you try to follow the instruction for RN 0.62+ versions. you might miss art which recently excluded from RN package
