### ISSUE TITLE
Android - not rendering properly with React Native 0.45.1

### ISSUE THREAD

**Issue by rkwd** [nerdyfactory/react-native-simple-gauge#8]
Similar to this issue - https://github.com/bgryszko/react-native-circular-progress/issues/64

That's what I currently get:
<img width="194" alt="screen shot 2017-07-06 at 4 27 23 pm" src="https://user-images.githubusercontent.com/21255318/27913391-9e66acae-6268-11e7-8983-cc15bf5595d6.png">

**Comment by JonghunYu** [comment]
@rkwd Hi thanks for reporting.
I will take a look at it.
